### ISSUE TITLE
没法启动

### ISSUE THREAD

**Issue by 2kk22** [RicardaY/YYS-ASSIST#1]
![屏幕截图 2024-04-05 101700](https://github.com/RicardaY/YYS-ASSIST/assets/165937666/f105a28e-e3de-4a2a-82f8-73551ed2fc44)
![屏幕截图 2024-04-05 101715](https://github.com/RicardaY/YYS-ASSIST/assets/165937666/d743fc9b-b14f-4ddb-8644-ab9eba3ca6e7)
![屏幕截图 2024-04-05 101631](https://github.com/RicardaY/YYS-ASSIST/assets/165937666/6da30054-627c-48a0-a1da-bfbd32bd4ede)

**Comment by 2kk22** [comment]
弄好了，少了个mfc组件，，，

**Comment by RicardaY** [comment]
可以加群交流
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年04月05日 10:52 收件人 ***@***.***> 抄送至 ***@***.***> 主题 Re: [RicardaY/YYS-ASSIST] 没法启动 (Issue #1) 
弄好了，少了个mfc组件，，，

**Comment by RicardaY** [comment]
已解决
